#!/bin/bash

# Check if all arguments present
if [[ $# -ne 2 ]]; then
  echo "Usage this syntax: kubeplugin [pods|nodes] [namespace]"
  exit 1
fi

RESOURCE_TYPE=$1
NAMESPACE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  echo "Resource: $RESOURCE_TYPE"
  echo "Namespace: $NAMESPACE"
  echo "Name: $NAME"
  echo "CPU: $CPU"
  echo -e "Memory: $MEMORY \n"
done
